service: moerss

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10
  usagePlan:
    quota:
      limit: 5000
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 200
      rateLimit: 100

functions:
  feed:
    handler: src/handlers/feed.handler
    memorySize: 1024
    timeout: 180
    runtime: nodejs6.10
    events:
      - http:
          path: feed
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                source: true
                type: false
