service: moerss

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  usagePlan:
    quota:
      limit: 5000
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 200
      rateLimit: 100

functions:
  hello:
    handler: index.hello
    events:
      - http:
          path: hello
          method: get
          cors: true
