service: ${file(./config.yml):service_name, 'moerss'}

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  stage: ${file(./config.yml):stage, 'dev'}
  region: ${file(./config.yml):region, 'us-east-1'}
  runtime: nodejs6.10
  environment:
    BUCKET_NAME: ${file(./config.yml):service_name, 'moerss'}-${file(./config.yml):stage, 'dev'}-bucket
    MERCURY_API_KEY: ${file(./config.yml):mercury_api_key, ''}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
            - ${file(./config.yml):service_name, 'moerss'}-${file(./config.yml):stage, 'dev'}-bucket/*
  usagePlan:
    quota:
      limit: 5000
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 200
      rateLimit: 100

functions:
  feed:
    handler: src/handlers/feed.handler
    memorySize: 1024
    timeout: 180
    runtime: nodejs6.10
    events:
      - http:
          path: feed
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                source: true
                type: false
                limit: false

resources:
  Resources:
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${file(./config.yml):service_name, 'moerss'}-${file(./config.yml):stage, 'dev'}-bucket

custom:
  webpackIncludeModules: true
